# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- devops

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  clean: 'all'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pip install -r requirements.txt'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'nosetests test'