# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- devops

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout Code'
  clean: 'all'

- task: UsePythonVersion@0
  displayName: 'Use Python 3'
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: Bash@3
  displayName: 'PIP Install'
  inputs:
    targetType: 'inline'
    script: 'pip install -r requirements.txt'

- task: Bash@3
  displayName: 'Unit Tests'
  inputs:
    targetType: 'inline'
    script: | 
      nosetests ./test

- task: ado-discord-webhook@1
  inputs:
    channelId: '598686758284296233'
    webhookKey: 'XVWtv9p2hkzd8rxLFYxMj2YCpaunjbzRyEpBs2uvbuf_lOF0kKMYutAJPvaxJxWWkRT0'
    messageType: 'content'
    content: 'Completed Build of RCSThumbnailGen'